### ISSUE TITLE
Wet_bulb() hangs

### ISSUE THREAD

**Issue by mreischer** [remcmurry/Psychropy#1]
Hi,
Your Wet_bulb will hang for temps close to zero.
I have run the Exel VBA version of this code against 1,000 USA weather stations and 8760 hour for each of typical hourly annual weather data (TMY3 data).  The algorithm crashes on too many of them.

The fix is simple.  In Wet_bulb() Instead of 
while abs((W_new - W_normal) / W_normal) > 0.00001:
Use 
while abs(W_new - W_normal) > 0.00001:
which avoids dividing by a number which may be very close (or equal) to zero.
Now instead of trying to converge to within .01% you are converging to within .00001 degrees, which should be overkill for most applications.

**Comment by remcmurry** [comment]
mreischer,
Thanks, that looks like a good way to go ... I had just traslated the original VBA and had not ever tested it near zero.  I feel like that tight a convergence might take a lot of resource if you are doing this calculation many times.  The equations used for this program come out of the ASHREA Handbook and might not be appropriate in that range, so i will look into that first.

If they do hold in that range, I will try to get an updated version up soon.   I will also look into timing a bit as well to see what the criteria should be to get resonable results for accuracy and timing.

remcmurry

**Comment by mreischer** [comment]
You are right about the convergence criteria.
I didn't presume to know other people's applications so I kept it tight.
Probably best to add a convergence criteria as a user parameter with a
looser default value.
python version is easy.
The Excel VBA version could use a named range which contains the epsilon
and a default if the name does not exist.
A max iteration count would also be helpful in case bad input data prevents
convergence.
I am running some tests now.
I'll let you know how they work.

Matthew Reischer, MSME
Northeastern Energy Consultants
Voice 856-448-4069
Fax 866-670-4065
MReischer@neecons.com

www.neecons.com
@matt_reischer http://twitter.com/intent/user?screen_name=matt_reischer
(Twitter)
LinkedIn http://www.linkedin.com/in/mreischer

**Comment by adlerlinhares** [comment]
i get ths error message when try to find the wet bulb temperature:

  File "C:\Users\adler\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\adler\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psycro.py", line 224, in <module>
    Twb= Wet_bulb(Tdb, RH, P)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psycro.py", line 148, in Wet_bulb
    W_new = Hum_rat(Tdb, result, P)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psycro.py", line 77, in Hum_rat
    Pws = Sat_press(Twb)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psycro.py", line 60, in Sat_press
    C6*TK**4 + C7*math.log(TK)) / 1000

ValueError: math domain error


do you know how to fix it?

**Comment by remcmurry** [comment]
What are the inputs causing the error?

**Comment by adlerlinhares** [comment]
I think the error is in  "W_new = Hum_rat(Tdb, result, P)" inside the while loop in "def Wet_bulb(Tdb, RH, P):"
are you sucessfully running this code?

**Comment by adlerlinhares** [comment]
enter the value for P:1035

enter the first input type:'Tdb'

enter first input value:30

enter the second input type:'RH'

enter second input value:60

enter the output type:'Twb'

enter the unit type (Imp or SI):'SI'
Traceback (most recent call last):

  File "<ipython-input-15-e106463e0cfb>", line 1, in <module>
    runfile('C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py', wdir='C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master')

  File "C:\Users\adler\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\adler\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 444, in <module>
    if __name__=='__main__': main()

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 441, in main
    result=psych(float(P),in0Type,float(in0Val),in1Type,float(in1Val),outType,unitType)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 395, in psych
    outVal = Wet_bulb(Tdb, RH, P)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 229, in Wet_bulb
    W_new = Hum_rat(Tdb, result, P)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 158, in Hum_rat
    Pws = Sat_press(Twb)

  File "C:/Users/adler/Documents/spyder-soad/Bokeh/Psychropy-master/psychropy.py", line 141, in Sat_press
    C6*TK**4 + C7*math.log(TK)) / 1000

ValueError: math domain error

**Comment by remcmurry** [comment]
Where:
P is the barometric pressure in PSI or Pa .
intypes indicator string for the corresponding
invalue parameter (ie Tdb, RH etc.)
invalues is the actual value associated with the type of parameter
(ie value of Wet bulb, Dew point, RH, or Humidity
Ratio etc.)
outType indicator string for the corresponding invalue parameter
unittype is the optional unit selector. Imp for Imperial, SI for
SI. Imp is default if omitted.
valid intypes:
Tdb Dry Bulb Temp F or C Valid for Input
*** it is highly Recommended Tdb be used as an input (can only
output/not use, if both other inputs are h and HR)
Twb Web Bulb Temp F or C Valid for Input
DP Dew point F or C Valid for input
RH RH between 0 and 1 Valid for input
W Humidity Ratio Mass Water/ Mass Dry Air Valid for input
h Enthalpy BTU/lb dry air or kJ/kg DA Valid for input
***Warning 0 state for Imp is ~0F, 0% RH ,and 1 ATM, 0 state
for SI is 0C, 0%RH and 1 ATM

as i copied out of the code instructions above the pressure should be on
the order of 100,000 if you are operating near atmospheric pressures, which
this code is designed around.  a good typical one would be P = 101325
pa(this is in pascals)

the RH as listed above should be entered as a number between 0 and 1 ... so
the number 60 is probably what is throwing that error.

I can look into it further if this does not get you on the right track.

Cheers

Robert (Robbie) McMurry
Assistant Development Engineer, Western Cooling Efficiency Center
Minister, Davis Bike Collective (Bike Forth)
remcmurry@gmail.com
mobile: (575) 323 4561

**Comment by mreischer** [comment]
Did you check how many times the loop is executing?  Is it converging or
diverging?
Wet Bulb uses Newton's Method to numerically estimate the value.  When I
was using it there were cases when the algorithm would not converge.  The
convergence criterion were not reasonable and had to be changed.  In any
event may help to plot the output of the while loop versus the loop counter.

Matthew Reischer, MSME
Northeastern Energy Consultants
Voice (856) 448-4069
Fax (866) 670-4065
MReischer@neecons.com

www.neecons.com
@matt_reischer <http://twitter.com/intent/user?screen_name=matt_reischer>
(Twitter)
LinkedIn <http://www.linkedin.com/in/mreischer>
